services:
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d:ro
      - ./RFID:/var/www/html
    depends_on:
      - php

  php:
    build:
      context: ./docker/php
    expose:
      - "9000"
    ports:
      - "8081:9000"
    volumes:
      - ./RFID:/var/www/html
    command: >
      sh -c "
        chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache &&
        chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache &&
        php-fpm
      "
    depends_on:
      - mysql

  mysql:
    build:
      context: ./docker/mysql
    container_name: rc-db
    platform: linux/x86_64
    ports:
      - "3307:3307"
    environment:
      - LANG=C.UTF-8
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=RFID
      - MYSQL_PASSWORD=09278401288Ian
    command: --port=3307
    volumes:
      - mysql-volume:/var/lib/mysql

networks:
  default:
    driver: bridge

volumes:
  mysql-volume:
    driver: local
